Added ban duration input types
tf2pickup-org/client pull request #2388
Opened 2023-09-05 15:37 UTC by EyalBenari

- Generic duration
- End date

2023-09-05 20:06 UTC, garrappachc requested changes

2023-09-05 20:29 UTC, EyalBenari commented on src/app/players/add-player-ban/add-player-ban.component.ts
> +function getDurationToDate(dateTimeString: string) {
done, but why?

2023-09-05 21:52 UTC, garrappachc approved these changes

2023-09-05 21:54 UTC, garrappachc commented on src/app/players/add-player-ban/add-player-ban.component.ts
> +function getDurationToDate(dateTimeString: string) {
Due to misleading `this` binding in functions. It's basically obsolete in modern js.

2023-09-06 10:05 UTC, merged

2023-09-06 10:05 UTC, garrappachc commented
Thank you!