Added tf2pickup.rs
tf2pickup-org/client pull request #837
Opened 2021-04-07 15:51 UTC by makemake-kbo

Added tf2pickup.rs branding. Logo is a WIP and will be changed later.

2021-04-07 16:06 UTC, garrappachc requested changes
The `tf2pickup_logo_white.png` file should be two times smaller (in each dimension) than `tf2pickup_logo_white@2x.png`. The `@2` version is picked up on high-density displays (4k monitors, mobile devices, etc.).

2021-04-07 16:06 UTC, garrappachc commented on src/environments/tf2pickup.rs.ts
> +  titleSuffix: 'tf2pickup.rs • Ex-Yu Team Fortress 2 Pickup-up games',
Typo: Pickup-up

2021-04-07 20:12 UTC, makemake-kbo commented
I updated the domain and fixed the typos. Im waiting for bobair to do the graphics so we should wait for her until we merge.
How about a version bump aswell?

2021-04-08 15:23 UTC, makemake-kbo commented
I removed them now. Thanks for the heads up!

2021-04-08 16:32 UTC, garrappachc approved these changes

2021-04-08 16:33 UTC, merged